# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYQMp9JM4wHgIY9mq3SIyHXwPOhvkZ8U
"""

import os
import subprocess
import sys

# --- SMART INSTALLATION FOR COLAB ---
# Yeh hissa check karega ke agar streamlit nahi hai (Colab mein), to install kar dega.
# Deployment (Streamlit Cloud) par yeh yeh error nahi dega.
try:
    import streamlit as st
except ImportError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "streamlit"])
    import streamlit as st

import pandas as pd
import numpy as np
import re
import ast
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(page_title="AI Job Recommender", layout="centered")

st.title("💼 AI Job Recommendation & Skill Gap Analyzer")
st.write("Paste your resume and get job recommendations with missing skills 🚀")

# -----------------------------
# LOAD DATA (SAFE LOADING)
# -----------------------------
@st.cache_data
def load_data():
    file_path = "Cleaned_Jobs_Resume.csv" # Corrected file path to use the generated CSV
    if os.path.exists(file_path):
        df = pd.read_csv(file_path, engine='python') # Added engine='python' to handle parsing issues
        # Skills column ko list mein convert karna
        df['skills'] = df['skills'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else [])
        # 'cleaned_job' column check (agar na ho to create karein)
        if 'cleaned_job' not in df.columns:
            df['cleaned_job'] = df['positionName'].fillna('') + " " + df['skills'].apply(lambda x: " ".join(x))
        return df
    else:
        st.error(f"❌ '{file_path}' file nahi mili! Please upload karein.")
        return None

jobs = load_data()

# -----------------------------
# CLEAN TEXT
# -----------------------------
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z ]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# -----------------------------
# SKILLS LIST (Expanded for better results)
# -----------------------------
skills_list = [
    "python", "java", "c++", "sql", "machine learning",
    "deep learning", "data analysis", "pandas", "numpy",
    "excel", "power bi", "tableau", "tensorflow",
    "nlp", "opencv", "communication", "teamwork", "react", "node"
]

def extract_skills(text):
    return [skill for skill in skills_list if skill in text.lower()]

# -----------------------------
# SKILL GAP & SUGGESTION
# -----------------------------
def skill_gap(user_skills, job_skills):
    return list(set(job_skills) - set(user_skills))

def suggest_skills(missing_skills):
    if len(missing_skills) == 0:
        return "✅ You already have all required skills!"
    return "📚 You should learn: " + ", ".join(missing_skills)

# -----------------------------
# USER INTERFACE
# -----------------------------
if jobs is not None:
    user_input = st.text_area("📄 Paste your resume here (Text format)")

    if st.button("🔍 Analyze Resume"):
        if not user_input.strip():
            st.warning("⚠ Please enter your resume text")
        else:
            with st.spinner('Analyzing...'):
                cleaned_input = clean_text(user_input)

                # TF-IDF Vectorization
                tfidf = TfidfVectorizer(max_features=5000, stop_words='english')
                job_matrix = tfidf.fit_transform(jobs['cleaned_job'])
                user_vector = tfidf.transform([cleaned_input])

                # Similarity Calculation
                scores = cosine_similarity(user_vector, job_matrix)
                top_jobs_idx = np.argsort(scores[0])[::-1][:5]

                # User Skills Extraction
                user_skills = extract_skills(cleaned_input)

                st.subheader("🧠 Your Detected Skills")
                if user_skills:
                    st.write(", ".join(user_skills))
                else:
                    st.info("No specific skills from our list detected.")

                st.subheader("💼 Top 5 Job Recommendations")

                for i in top_jobs_idx:
                    row = jobs.iloc[i]
                    job_title = row['positionName']
                    job_skills = row['skills']

                    missing = skill_gap(user_skills, job_skills)
                    suggestion = suggest_skills(missing)

                    with st.expander(f"💼 {job_title} (Match Score: {scores[0][i]:.2f})"):
                        st.write("*Required Skills:*", ", ".join(job_skills) if job_skills else "N/A")
                        st.write("*Missing Skills:*", ", ".join(missing) if missing else "None")
                        st.info(f"🚀 {suggestion}")

